name: Update BLT Hash

on:
  push:
    branches:
      - autoupdate

env:
  IDENT: wolfhud                        #Identifier for the mod.
  TEX_IDENT: fed_inv                    #Identifier for the texture override
  TEX_HASH : 6d4d3621818333a94df36e2492b9a730481d4125916ef3c8f7bde337f08a6ff2
  BRANCH_DL: master                     #Branch hosting the stable release version.
  BRANCH_UPD: autoupdate                #Branch hosting the meta.json and SuperBLT_Hasher.py files.
  CHANGELOG: autoupdate/Changelog.md    #Branch + Filename for the Changelog-File.

jobs:
  update-hash:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    
    steps:
    - name: Setup Python
      uses: actions/setup-python@v1.1.1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Checkout Mod Branch
      uses: actions/checkout@v2
      with:
        ref: ${{ env.BRANCH_DL }}
        path: "${{ github.workspace }}/${{ env.BRANCH_DL }}/"
    - name: Checkout Updater Branch
      uses: actions/checkout@v2
      with:
        ref: ${{ env.BRANCH_UPD }}
        token: ${{ github.token }}
        path: "${{ github.workspace }}/${{ env.BRANCH_UPD }}/"
#    - name: Extract Override Mod
#      uses: montudor/action-zip@v0.1.0
#      with:
#        args: unzip -qq ${{ github.workspace }}/${{ env.BRANCH_UPD }}/${{ env.TEX_IDENT }}.zip -d ${{ github.workspace }}/${{ env.TEX_IDENT }}/
    - name: Calculate Hash
      id: hash
      run: |
        echo ::set-env name=HASH::$(python $GITHUB_WORKSPACE/$BRANCH_UPD/SuperBLT_Hasher.py $GITHUB_WORKSPACE/$BRANCH_DL/)
#    - name: Calculate Override Hash
#      id: texture_hash
#      run: |
#        echo ::set-env name=TEX_HASH::$(python $GITHUB_WORKSPACE/$BRANCH_UPD/SuperBLT_Hasher.py "$GITHUB_WORKSPACE/$TEX_IDENT/Federal Inventory/")
    - name: Create local changes
      run: |
        cat <<EOM >$GITHUB_WORKSPACE/$BRANCH_UPD/meta.json
        [
            {
                "ident": "$IDENT",
                "hash": "$HASH",
                "download_url": "https://github.com/$GITHUB_REPOSITORY/archive/$BRANCH_DL.zip",
                "patchnotes_url": "https://github.com/$GITHUB_REPOSITORY/releases/latest"
            },
            {
                "ident": "$TEX_IDENT",
                "hash": "$TEX_HASH",
                "download_url": "https://github.com/$GITHUB_REPOSITORY/raw/$BRANCH_UPD/$TEX_IDENT.zip",
                "patchnotes_url": "https://github.com/$GITHUB_REPOSITORY/releases/latest"
            }
        ]
        EOM
    - name: Commit files
      run: |
        cd $GITHUB_WORKSPACE/$BRANCH_UPD/
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Change Hash for new Version." -a
    - name: Push changes
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ github.token }}
        branch: ${{ env.BRANCH_UPD }}
        directory: ${{ github.workspace }}/${{ env.BRANCH_UPD }}/
